[package]
name = "nexhub_service"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = { version = "1.0", features = ["kv-mem"] }
serde = { version = "1.0" }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.32", features = ["rt-multi-thread"] }
